/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/child_wallet_backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface SignatureReply {
    signature: Uint8Array;
}
export interface PublicKeyReply {
    publicKey: Uint8Array;
}
export interface child_wallet_backendInterface {
    createPublicKey(index: number): Promise<PublicKeyReply>;
    getPublicKey(index: number): Promise<PublicKeyReply>;
    get_caller(): Promise<Principal>;
    sign(message: Uint8Array, index: number): Promise<SignatureReply>;
    signText(message: string, index: number): Promise<SignatureReply>;
}
export class Child_wallet_backend implements child_wallet_backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async createPublicKey(arg0: number): Promise<PublicKeyReply> {
        const result = await this.actor.createPublicKey(arg0);
        return result;
    }
    async getPublicKey(arg0: number): Promise<PublicKeyReply> {
        const result = await this.actor.getPublicKey(arg0);
        return result;
    }
    async get_caller(): Promise<Principal> {
        const result = await this.actor.get_caller();
        return result;
    }
    async sign(arg0: Uint8Array, arg1: number): Promise<SignatureReply> {
        const result = await this.actor.sign(arg0, arg1);
        return result;
    }
    async signText(arg0: string, arg1: number): Promise<SignatureReply> {
        const result = await this.actor.signText(arg0, arg1);
        return result;
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Child_wallet_backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Child_wallet_backend(actor);
}
